name: azblob
description: |
  A trivial Azure Blob Storage client.
  You can get and put Blob on server side dart.
version: 2.4.0
homepage: https://github.com/kkazuo/dart-azblob

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  http: ^1.1.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.16.8
